name: Tests CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'ignite'
      - uses: actions/checkout@v3
        with:
          repository: 'TestingResearchIllinois/NonDex'
          path: 'NonDex'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: Install Dependencies
        run: mvn -f ./ignite/pom.xml clean install -DskipTests
      - name: Cloning NonDex & checkout
        run: git -C ./NonDex checkout 85b3782bb43fa20c89af7d17fb32c9f0182ad269
      - name: Building NonDex
        run: mvn -f ./NonDex/pom.xml clean install -DskipTests -Dcheckstyle.skip
      - name: Installing NonDex
        run: >
          mvn -f ./NonDex/pom.xml install:install-file
          -Dfile=./nondex-maven-plugin/target/nondex-maven-plugin-2.1-SNAPSHOT.jar
          -DgroupId=edu.illinois
          -DartifactId=nondex-maven-plugin
          -Dversion=2.1 -Dpackaging=jar -DgeneratePom=true -DcreateChecksum=true
      - name: Run NonDex
        run: mvn -f ./ignite/pom.xml edu.illinois:nondex-maven-plugin:2.1-SNAPSHOT:nondex -pl modules/configuration
